MAIL_USERNAME: ''
MAIL_PASSWORD: ''
DOMAIN_NAME: ''
ADMIN_NAME: admin
ADMIN_EMAIL: admin@cywin.cn
ADMIN_PASSWORD: admin
ROLES: [admin, investor, leader]

# GOOGLE ANYLITCS
GA_ID: ''
GA_URL: ''

# set system locale en or zh-CN, default is zh-CN
LOCALE: zh-CN
# show demo tip on the top, comment it if no need
# DEMO_TIP: 1

# SECRET_KEY_BASE
SECRET_KEY_BASE: ''
# sidekiq namespace
SIDEKIQ_NAMESPACE: cywin
# built-in test enable 1 / disable 0
BIT: 0
