MAIL_USERNAME: ''
MAIL_PASSWORD: ''
DOMAIN_NAME: ''
ADMIN_NAME: admin
ADMIN_EMAIL: admin@cywin.cn
ADMIN_PASSWORD: admin
ROLES: [admin, investor, leader]

# GOOGLE ANYLITCS
GA_ID: ''
GA_URL: ''

# set system locale en or zh-CN, default is zh-CN
LOCALE: zh-CN

# SECRET_KEY_BASE
SECRET_KEY_BASE: ''
# sidekiq namespace
SIDEKIQ_NAMESPACE: cywin
# Redis configuration
REDIS_URL: ''
REDIS_PASSWORD: ''
REDIS_HOST: 'localhost'
REDIS_PORT: '6379'
# built-in test enable 1 / disable 0
BIT: 0